development:
  adapter: mysql2
  encoding: utf8
  database: assetsonar_api_development
  username: root
  password: root
  variables:
    sql_mode: TRADITIONAL

test:
  adapter: mysql2
  encoding: utf8
  database: assetsonar_api_test
  username: root
  password: root
  variables:
    sql_mode: TRADITIONAL
